### ISSUE TITLE
Application Won't Support Max. Connection

### ISSUE THREAD

**Issue by IIIPeAceIII** [archdvx/wxdfast#101]
The application doesn't download any file with upto max. connection (i.e. 30), only support upto 16 connections.
The app just doesn't work when connections are specified more than 16 connections in download box.

**Comment by archdvx** [comment]
I check aria2 documentation for "max-connection-per-server" and it hasn't max value.
But you are right it supports 16 as maximum value.
**Thanks** for your report.
