### ISSUE TITLE
Downloads from SourceForge fail

### ISSUE THREAD

**Issue by smaragdus** [archdvx/wxdfast#103]
Any time I try to download files from [SourceForge](https://sourceforge.net/) the downloads fail.

I get this tray error message:

`Downloaded ended with error`

**screen 1:**

![wxDownload Fast 0 70 3 - 2022-04-24 - error - 001](https://user-images.githubusercontent.com/9025757/164969942-05c35b16-d76d-4b10-a286-56896a134d8f.png)

- [File 1](https://netix.dl.sourceforge.net/project/copyhandler/copyhandler/1.46/chsetup-1.46.exe) (**chsetup-1.46.exe**)
- [File 2](https://netix.dl.sourceforge.net/project/copyhandler/copyhandler/1.46/ch-portable-1.46.zip) (**ch-portable-1.46.zip**)

[Download Directory](https://sourceforge.net/projects/copyhandler/files/copyhandler/1.46/)

**screen 2:**

![wxDownload Fast 0 70 3 - 2022-04-24 - error - 002](https://user-images.githubusercontent.com/9025757/164970452-f30fed6c-5407-4c3e-a3de-56d1ef4dbab1.png)

**screen 3:**

![wxDownload Fast 0 70 3 - 2022-04-24 - error - 003](https://user-images.githubusercontent.com/9025757/164970470-afc6eeee-ed02-4a22-bd18-1e3f33fd6c5b.png)

Please confirm that downloads from [SourceForge](https://sourceforge.net/) do not work using [wxDownload Fast](https://github.com/archdvx/wxdfast) version [0.70.3](https://github.com/archdvx/wxdfast/releases/tag/v0.70.3).

**Comment by archdvx** [comment]
Thanks for your report.
I try investigate and fix (if needed) ASAP :)

**Comment by smaragdus** [comment]
@archdvx 

Thanks.

After I do some more testing it may happen that I open more issues.

Thanks for resurrecting the  [original project](https://sourceforge.net/projects/dfast/) which was abandoned long ago!

**Comment by archdvx** [comment]
> After I do some more testing it may happen that I open more issues.

I hope I will time for fix it.
But any issue which will be fixed and go to better wxDownloadFast is welcome.

**Comment by archdvx** [comment]
As I thought, problem was with "root.cert" on Windows.
Now fixed.
![fixed](https://user-images.githubusercontent.com/15364517/170867497-9b01608c-02c6-4009-9c85-5fec3357a592.png)
I will make new release today.

**Comment by archdvx** [comment]
> I may open some more issues suggesting several tiny enhancements which you may consider for future releases.

Every suggestion is welcome.
